import type { Metadata } from "next";
import { Geist, Host_Grotesk, Bokor } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
});
const bokor = Bokor({
  variable: "--font-host-bokor",
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${hostGrotesk.variable} font-main text-primary antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
