import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
const exensaGrotest = localFont({
  src: "../fonts/ExensaGrotesk-Regular.ttf",
  variable: "--font-exensa-grotesk",
});

const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${hostGrotesk.className} ${exensaGrotest.variable} text-primary antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
